-- MySQL Script generated by MySQL Workbench
-- Tue Oct 11 23:54:16 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Table `T_MANAGER_man`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_MANAGER_man` (
  `man_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `man_pseudo` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `man_pw` CHAR(128) CHARACTER SET 'ascii' COLLATE 'ascii_bin' NOT NULL,
  PRIMARY KEY (`man_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_PROFILE_pfl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_PROFILE_pfl` (
  `pfl_first_name` VARCHAR(80) NOT NULL,
  `pfl_last_name` VARCHAR(80) NOT NULL,
  `pfl_role` CHAR(1) NOT NULL DEFAULT 'F',
  `pfl_registration_date` DATE NOT NULL,
  `pfl_active` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `man_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`man_id`),
  CONSTRAINT `fk_T_PROFILE_pfl_T_MANAGER_man1`
    FOREIGN KEY (`man_id`)
    REFERENCES `T_MANAGER_man` (`man_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_NEWS_new`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_NEWS_new` (
  `new_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `new_title` VARCHAR(200) NOT NULL,
  `new_content` VARCHAR(500) NOT NULL,
  `new_date` DATETIME NOT NULL,
  `man_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`new_id`),
  INDEX `fk_T_ACTUALITE_actu_T_MANAGER_man1_idx` (`man_id` ASC),
  CONSTRAINT `fk_T_ACTUALITE_actu_T_MANAGER_man1`
    FOREIGN KEY (`man_id`)
    REFERENCES `T_MANAGER_man` (`man_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_QUIZ_quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_QUIZ_quiz` (
  `quiz_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quiz_title` VARCHAR(200) NOT NULL,
  `quiz_image` VARCHAR(300) NOT NULL,
  `quiz_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `man_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`quiz_id`),
  INDEX `fk_T_QUIZ_quiz_T_MANAGER_man1_idx` (`man_id` ASC),
  CONSTRAINT `fk_T_QUIZ_quiz_T_MANAGER_man1`
    FOREIGN KEY (`man_id`)
    REFERENCES `T_MANAGER_man` (`man_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_MATCH_match`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_MATCH_match` (
  `match_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `match_title` VARCHAR(200) NOT NULL,
  `match_code` CHAR(8) NOT NULL,
  `match_start_date` DATETIME NULL,
  `match_end_date` DATETIME NULL,
  `match_show_answers` TINYINT NOT NULL DEFAULT 1,
  `match_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 0,
  `quiz_id` INT UNSIGNED NOT NULL,
  `man_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`match_id`),
  INDEX `fk_T_MATCH_MATCH_T_QUIZ_QUIZ1_idx` (`quiz_id` ASC),
  INDEX `fk_T_MATCH_match_T_MANAGER_man1_idx` (`man_id` ASC),
  CONSTRAINT `fk_T_MATCH_MATCH_T_QUIZ_QUIZ1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `T_QUIZ_quiz` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_T_MATCH_match_T_MANAGER_man1`
    FOREIGN KEY (`man_id`)
    REFERENCES `T_MANAGER_man` (`man_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_PLAYER_player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_PLAYER_player` (
  `player_pseudo` VARCHAR(20) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `player_score` FLOAT UNSIGNED NOT NULL DEFAULT 0,
  `match_id` INT UNSIGNED NOT NULL,
  INDEX `fk_T_JOUEUR_jou_T_MATCH_match1_idx` (`match_id` ASC),
  PRIMARY KEY (`player_pseudo`, `match_id`),
  CONSTRAINT `fk_T_JOUEUR_jou_T_MATCH_match1`
    FOREIGN KEY (`match_id`)
    REFERENCES `T_MATCH_match` (`match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_QUESTION_qst`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_QUESTION_qst` (
  `qst_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `qst_content` VARCHAR(200) NOT NULL,
  `qst_image` VARCHAR(300) NULL,
  `qst_order` TINYINT UNSIGNED NOT NULL,
  `qst_enabled` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `quiz_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`qst_id`),
  INDEX `fk_T_QUESTION_QST_T_QUIZ_QUIZ1_idx` (`quiz_id` ASC),
  CONSTRAINT `fk_T_QUESTION_QST_T_QUIZ_QUIZ1`
    FOREIGN KEY (`quiz_id`)
    REFERENCES `T_QUIZ_quiz` (`quiz_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `T_ANSWER_ans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `T_ANSWER_ans` (
  `ans_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ans_content` VARCHAR(200) NOT NULL,
  `ans_image` VARCHAR(300) NULL,
  `ans_valid` TINYINT UNSIGNED NOT NULL,
  `qst_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ans_id`),
  INDEX `fk_T_REPONSE_REP_T_QUESTION_QST1_idx` (`qst_id` ASC),
  CONSTRAINT `fk_T_REPONSE_REP_T_QUESTION_QST1`
    FOREIGN KEY (`qst_id`)
    REFERENCES `T_QUESTION_qst` (`qst_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
