DROP TABLE IF EXISTS T_ANSWER_ans;
DROP TABLE IF EXISTS T_QUESTION_qst;
DROP TABLE IF EXISTS T_PLAYER_player;
DROP TABLE IF EXISTS T_MATCH_match;
DROP TABLE IF EXISTS T_QUIZ_quiz;
DROP TABLE IF EXISTS T_NEWS_new;
DROP TABLE IF EXISTS T_PROFILE_pfl;
DROP TABLE IF EXISTS T_MANAGER_man;